'use client';

import { ArrowLeft,ArrowRight,FileText,Pencil,Trash2 } from 'lucide-react';
import { PointerEvent,useEffect,useMemo,useRef,useState } from 'react';
import AppTopbar from '../AppTopbar';import AppSidebar from '../AppSidebar';import { createBrowserSupabaseClient } from '../../lib/supabase/client';import '../app-topbar.css';import '../app-sidebar.css';import './notes-page.css';
type Note={id:string;subject:string;body:string;created_at:string;updated_at:string;demo?:boolean};
const demos:Note[]=[{id:'demo-q4',subject:'Planejamento Q4',body:'Definir estratégias de crescimento, revisar metas do time, alinhar campanhas de marketing e analisar resultados do Q3. Foco em performance e expansão de mercado.',created_at:'2026-09-08T10:24:00-03:00',updated_at:'2026-09-08T10:24:00-03:00',demo:true},{id:'demo-comercial',subject:'Reunião Comercial',body:'Revisar oportunidades em aberto, próximos contatos e propostas prioritárias. Organizar os pontos de negociação para acelerar decisões.',created_at:'2026-09-08T14:10:00-03:00',updated_at:'2026-09-08T14:10:00-03:00',demo:true},{id:'demo-marketing',subject:'Estratégia de Marketing',body:'Mapear campanhas do mês, conteúdos de maior impacto e novas oportunidades de aquisição. Priorizar ações com melhor retorno e clareza de mensagem.',created_at:'2026-09-09T09:15:00-03:00',updated_at:'2026-09-09T09:15:00-03:00',demo:true}];
const fmt=(date:string)=>new Date(date).toLocaleString('pt-BR',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).replace(',',' •');
export default function AnotacoesPage(){const supabase=useMemo(()=>createBrowserSupabaseClient(),[]);const[notes,setNotes]=useState<Note[]>([]);const[loading,setLoading]=useState(true);const[activeIndex,setActiveIndex]=useState(0);const[dragX,setDragX]=useState(0);const[dragging,setDragging]=useState(false);const startX=useRef(0);const lastX=useRef(0);const lastTime=useRef(0);const velocity=useRef(0);
useEffect(()=>{let alive=true;(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){if(alive)setLoading(false);return}const{data}=await supabase.from('notes').select('id,subject,body,created_at,updated_at').order('updated_at',{ascending:false});if(alive){setNotes((data||[]) as Note[]);setLoading(false)}})();return()=>{alive=false}},[supabase]);
const cards=[...notes,...demos];const carouselCards=cards.length?cards:demos;const count=carouselCards.length;const move=(d:number)=>setActiveIndex(i=>(i+d+count)%count);const visible=[-2,-1,0,1,2].map(offset=>({note:carouselCards[(activeIndex+offset+count)%count],offset}));
const onPointerDown=(e:PointerEvent<HTMLDivElement>)=>{if((e.target as HTMLElement).closest('button'))return;e.currentTarget.setPointerCapture(e.pointerId);startX.current=e.clientX;lastX.current=e.clientX;lastTime.current=performance.now();velocity.current=0;setDragging(true);setDragX(0)};
const onPointerMove=(e:PointerEvent<HTMLDivElement>)=>{if(!dragging)return;const now=performance.now();const dt=Math.max(1,now-lastTime.current);velocity.current=(e.clientX-lastX.current)/dt;lastX.current=e.clientX;lastTime.current=now;setDragX(e.clientX-startX.current)};
const finishDrag=()=>{if(!dragging)return;const projected=dragX+velocity.current*150;setDragging(false);if(Math.abs(projected)>70)move(projected<0?1:-1);setDragX(0)};
const cardTransform=(offset:number)=>{const step=275;const progress=Math.max(-1,Math.min(1,dragX/step));const distance=Math.abs(offset+progress);const scale=Math.max(.68,1.08-distance*.25);const opacity=Math.max(.22,1-distance*.35);return {transform:`translate(calc(-50% + ${offset*step+dragX}px),-50%) scale(${scale})`,opacity,zIndex:Math.round(10-distance*2)} as React.CSSProperties};
return <><AppSidebar/><AppTopbar/><main className="notes-page"><section className="notes-shell"><div className="notes-heading"><div><span>ANOTAÇÕES</span><h1>Suas ideias, <em>sempre à mão.</em></h1><p>Registros de reuniões, decisões e próximos passos em um só lugar.</p></div><div className="notes-count">{loading?'…':cards.length}<small>anotações</small></div></div><div className={`notes-carousel ${dragging?'is-dragging':''}`} aria-label="Carrossel de anotações"><button className="notes-carousel-arrow left" onClick={()=>move(-1)} aria-label="Anterior"><ArrowLeft/></button><div className="notes-carousel-stage" onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={finishDrag} onPointerCancel={finishDrag}>{visible.map(({note,offset})=><article className={`saved-note-card ${offset===0?'is-active':''}`} style={cardTransform(offset)} key={`${note.id}-${offset}`}><div className="saved-note-top"><div className="saved-note-icon"><FileText/></div><div className="saved-note-actions"><button aria-label="Editar"><Pencil/></button><button aria-label="Excluir" disabled={note.demo}><Trash2/></button></div></div><span className="saved-note-label">Anotação</span><h2>{note.subject}</h2><time>{fmt(note.updated_at)}</time><p>{note.body}</p><div className="saved-note-bottom"><button>Ver anotação <ArrowRight/></button><div className={`note-bars bars-${Math.abs(offset)%3}`}><i/><i/><i/><i/></div></div></article>)}</div><button className="notes-carousel-arrow right" onClick={()=>move(1)} aria-label="Próxima"><ArrowRight/></button></div><div className="notes-carousel-dots">{carouselCards.map((note,i)=><button key={note.id} className={i===activeIndex?'active':''} onClick={()=>setActiveIndex(i)} aria-label={`Anotação ${i+1}`}/>)}</div></section></main></>}
