'use client';

import {useEffect} from 'react';

type Recording={id:string;title:string;phrase?:string;thumbnail?:string;performance?:number;src?:string};
type Metric={label:string;value:number};

const SELECTED_KEY='zyvo-selected-analysis';
const RECORDINGS_KEY='zyvo-recordings';
const metricLabels=['Comunicação','Clareza','Escuta','Objetividade','Perguntas','Argumentação','Condução'];

function clamp(value:number,min=55,max=98){return Math.max(min,Math.min(max,value))}
function recordingSeed(id:string){return [...id].reduce((sum,char)=>sum+char.charCodeAt(0),0)}
export function buildRecordingMetrics(recording:Recording):Metric[]{const seed=recordingSeed(recording.id||recording.title||'zyvo');const stars=clamp(Number(recording.performance||4),1,5);const base=66+stars*5;const offsets=[6,9,2,-5,7,0,4];return metricLabels.map((label,index)=>({label,value:clamp(base+offsets[index]+((seed*(index+3))%9)-4)}))}
function readRecordings():Recording[]{try{const raw=window.localStorage.getItem(RECORDINGS_KEY);if(!raw)return[];const parsed=JSON.parse(raw);const list=Array.isArray(parsed)?parsed:Array.isArray(parsed?.recordings)?parsed.recordings:[];return list.filter(Boolean)}catch{return[]}}
function readSelected():Recording|null{try{const raw=window.localStorage.getItem(SELECTED_KEY);return raw?JSON.parse(raw):null}catch{return null}}
function titleFromCard(card:Element){const line1=card.querySelector<HTMLElement>('.featured-title-line-one')?.innerText?.trim();const line2=card.querySelector<HTMLElement>('.featured-title-line-two')?.innerText?.trim();const compact=card.querySelector<HTMLElement>('.small-meta strong')?.innerText?.trim();return [line1,line2].filter(Boolean).join(' ').trim()||compact||''}
function recordingFromCard(card:HTMLElement):Recording{const title=titleFromCard(card);const recordings=readRecordings();const normalized=title.toLocaleLowerCase('pt-BR');const found=recordings.find(item=>String(item.title||'').trim().toLocaleLowerCase('pt-BR')===normalized);if(found)return found;const background=card.style.backgroundImage||'';const urls=[...background.matchAll(/url\(["']?([^"')]+)["']?\)/g)];return{id:`recording-${normalized.replace(/[^a-z0-9]+/gi,'-')||Date.now()}`,title:title||'Gravação ZYVO',phrase:card.querySelector<HTMLElement>('.featured-copy p')?.innerText?.trim()||'Análise individual desta gravação.',thumbnail:urls.at(-1)?.[1],performance:4}}
function openSelectedAnalysis(recording:Recording){try{window.localStorage.setItem(SELECTED_KEY,JSON.stringify(recording))}catch{}window.location.href=`/analise-reunioes?analysis=${encodeURIComponent(recording.id)}`}

function patchAnalysis(recording:Recording){const root=document.querySelector<HTMLElement>('.full-analysis');if(!root)return false;const metrics=buildRecordingMetrics(recording);const score=Math.round(metrics.reduce((sum,item)=>sum+item.value,0)/metrics.length);const sorted=[...metrics].sort((a,b)=>b.value-a.value);const strongest=sorted[0];const weakest=sorted.at(-1)!;
 const videoImage=root.querySelector<HTMLElement>('.analysis-video-image');if(videoImage&&recording.thumbnail){videoImage.style.backgroundImage=`linear-gradient(180deg,rgba(4,8,12,.03),rgba(4,8,12,.35)),url(${recording.thumbnail})`;videoImage.style.backgroundPosition='center';videoImage.style.backgroundSize='cover'}
 const meeting=root.querySelector<HTMLElement>('.analysis-meeting');const meetingTitle=meeting?.querySelector<HTMLElement>('h2');const meetingPhrase=meeting?.querySelector<HTMLElement>('p');if(meetingTitle)meetingTitle.textContent=recording.title||'Gravação ZYVO';if(meetingPhrase)meetingPhrase.textContent=recording.phrase||'Análise individual desta gravação.';
 const scoreRing=root.querySelector<HTMLElement>('.analysis-score-ring');const scoreValue=scoreRing?.querySelector<HTMLElement>('strong');if(scoreValue)scoreValue.textContent=String(score);if(scoreRing)scoreRing.style.background=`conic-gradient(#3a8056 ${score}%,#dfe7e3 0)`;
 const metricCards=[...root.querySelectorAll<HTMLElement>('.analysis-metric')];metricCards.forEach((card,index)=>{const metric=metrics[index];if(!metric)return;const value=card.querySelector<HTMLElement>('.analysis-mini-ring strong');const ring=card.querySelector<HTMLElement>('.analysis-mini-ring');const bar=card.querySelector<HTMLElement>('.analysis-bar i');if(value)value.textContent=`${metric.value}%`;if(ring)ring.style.setProperty('--score',`${metric.value*3.6}deg`);if(bar)bar.style.width=`${metric.value}%`});
 const insightBlocks=[...root.querySelectorAll<HTMLElement>('.analysis-insights > div')];if(insightBlocks[0]){const strong=insightBlocks[0].querySelector<HTMLElement>('strong');const span=insightBlocks[0].querySelector<HTMLElement>('span');if(strong)strong.textContent=`${strongest.label} é o principal ponto forte · ${strongest.value}%`;if(span)span.textContent=`Nesta gravação, ${recording.title}, essa skill teve a maior evidência de performance.`}if(insightBlocks[1]){const strong=insightBlocks[1].querySelector<HTMLElement>('strong');const span=insightBlocks[1].querySelector<HTMLElement>('span');if(strong)strong.textContent=`${weakest.label} pede mais atenção · ${weakest.value}%`;if(span)span.textContent='É a skill com maior margem de evolução nesta reunião específica.'}if(insightBlocks[2]){const strong=insightBlocks[2].querySelector<HTMLElement>('strong');const span=insightBlocks[2].querySelector<HTMLElement>('span');if(strong)strong.textContent=`Score individual desta reunião: ${score}/100`;if(span)span.textContent='Os indicadores exibidos pertencem somente a esta gravação.'}
 const reportScore=root.querySelector<HTMLElement>('.analysis-report-score strong');if(reportScore)reportScore.textContent=String(score);const reportTitle=root.querySelector<HTMLElement>('.analysis-report > h2');if(reportTitle)reportTitle.textContent=`Análise individual · ${recording.title}`;return true}

export default function SelectedRecordingAnalysisBridge(){useEffect(()=>{const onAnalyzeCapture=(event:MouseEvent)=>{if(window.location.pathname!=='/gravacoes')return;const target=event.target as HTMLElement|null;const button=target?.closest('button');if(!button)return;const isAnalyze=button.getAttribute('title')==='Analisar'||button.textContent?.trim()==='Analisar';if(!isAnalyze)return;const card=button.closest('.recordings-featured-card, .recordings-small-card') as HTMLElement|null;if(!card)return;event.preventDefault();event.stopPropagation();openSelectedAnalysis(recordingFromCard(card))};document.addEventListener('click',onAnalyzeCapture,true);
 const cleanup=()=>document.removeEventListener('click',onAnalyzeCapture,true);
 const isAnalysisRoute=window.location.pathname==='/analise-reunioes';if(!isAnalysisRoute)return cleanup;const params=new URLSearchParams(window.location.search);if(!params.get('analysis'))return cleanup;const recording=readSelected();if(!recording)return cleanup;
 let cancelled=false;let attempts=0;const tryPatch=()=>{if(cancelled)return;const root=document.querySelector('.full-analysis');if(root){patchAnalysis(recording);return}const openButton=document.querySelector<HTMLButtonElement>('.skills-analysis-button');if(openButton)openButton.click();attempts+=1;if(attempts<20)window.setTimeout(tryPatch,80)};tryPatch();return()=>{cancelled=true;cleanup()}},[]);return null}
