'use client';

import { Check, Crown, Gem, Sparkles } from 'lucide-react';
import { useState } from 'react';
import AppTopbar from '../AppTopbar';
import AppSidebar from '../AppSidebar';
import '../app-topbar.css';
import '../app-sidebar.css';
import './pricing.css';

type Plan = { key:string; name:string; eyebrow:string; monthly:number; description:string; aiLabel:string; aiLimit:string; features:string[]; cta:string; note:string; Icon:typeof Sparkles; featured?:boolean };

const plans:Plan[]=[
{key:'free',name:'Free',eyebrow:'PARA COMEÇAR',monthly:0,description:'O essencial da ZYVO para conhecer uma nova forma de se reunir.',aiLabel:'ZYVO IA · uso essencial',aiLimit:'20 interações de IA / mês',features:['Reuniões de até 40 minutos','Até 5 participantes','Vídeo em HD','Chat e anotações essenciais','Filtros e fundos básicos','Skills com visão básica de performance','Sem gravação de reuniões'],cta:'Começar grátis',note:'Sem cartão. Ideal para experimentar a ZYVO.',Icon:Sparkles},
{key:'pro',name:'Pro',eyebrow:'PARA PROFISSIONAIS',monthly:79.9,description:'Mais inteligência, performance e ferramentas para quem se reúne todos os dias.',aiLabel:'ZYVO IA · uso avançado',aiLimit:'300 interações de IA / mês',features:['Reuniões de até 30 horas','Até 100 participantes','Vídeo em Full HD','Gravações e biblioteca','Skills completas de performance','Resumo e insights pós-reunião','Análise de comunicação e condução','Ferramentas flutuantes e filtros ZYVO'],cta:'Escolher Pro',note:'A escolha ideal para uso profissional recorrente.',Icon:Crown,featured:true},
{key:'premium',name:'Premium',eyebrow:'PARA ALTA PERFORMANCE',monthly:197,description:'Capacidade ampliada e IA para quem transforma reuniões em decisões e resultados.',aiLabel:'ZYVO IA · uso intensivo',aiLimit:'1.000 interações de IA / mês',features:['Tudo do plano Pro','Até 300 participantes','Histórico completo de Skills','Análises avançadas de reuniões','Insights e recomendações aprofundadas','Maior capacidade para gravações','Recursos avançados de anfitrião','Suporte prioritário'],cta:'Escolher Premium',note:'Para profissionais, líderes e equipes de alta performance.',Icon:Gem}
];
const money=(value:number)=>value.toLocaleString('pt-BR',{minimumFractionDigits:value===0?0:2,maximumFractionDigits:2});
export default function PlanosPage(){const[billing,setBilling]=useState<'monthly'|'annual'>('monthly');return <><AppSidebar/><AppTopbar/><main className="pricing-page"><section className="pricing-shell"><div className="pricing-kicker">PLANOS E PREÇOS</div><div className="billing-toggle" role="group" aria-label="Período de cobrança"><button className={billing==='monthly'?'active':''} onClick={()=>setBilling('monthly')}>Mensal</button><button className={billing==='annual'?'active':''} onClick={()=>setBilling('annual')}>Anual <span>-20%</span></button></div><div className="pricing-grid">{plans.map(({key,name,eyebrow,monthly,description,aiLabel,aiLimit,features,cta,note,Icon,featured})=>{const value=billing==='annual'?monthly*.8:monthly;return <article key={key} className={`price-card ${featured?'featured':''}`}><div className="price-card-top"><div className="plan-icon"><Icon/></div>{featured&&<span className="choice-badge">MAIS ESCOLHIDO</span>}</div><div className="plan-eyebrow">{eyebrow}</div><h2>{name}</h2><div className="plan-price"><span>R$</span> {money(value)}{monthly>0&&<small>/mês</small>}</div>{billing==='annual'&&monthly>0&&<div className="annual-note">valor mensal equivalente · cobrança anual</div>}<p className="plan-description">{description}</p><div className="ai-allowance"><div className="ai-allowance-head"><Sparkles/><span>{aiLabel}</span></div><strong>{aiLimit}</strong></div><div className="plan-divider"/><ul>{features.map(feature=><li key={feature}><span className="check"><Check/></span>{feature}</li>)}</ul><button className="plan-cta">{cta}</button><p className="plan-note">{note}</p></article>})}</div><div className="pricing-footnote"><strong>Como funciona a ZYVO IA?</strong><span>1 interação corresponde a 1 mensagem enviada à inteligência da ZYVO. O limite é renovado a cada ciclo mensal do plano.</span></div></section></main></>}
